name: Deploy RingCentral Node.js project to Azure Function App

on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - closed

env:
  AZURE_FUNCTIONAPP_NAME: 'ringcentral-service'   # Your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'            # Path to function app project
  NODE_VERSION: '20.x'                            # Node.js version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup Node.js ${{ env.NODE_VERSION }}'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Install Dependencies & Build'
        shell: bash
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # Ensure this secret is correctly set in GitHub Secrets
